### ISSUE TITLE
BUG: Hydration mismatch

### ISSUE THREAD

**Issue by nicogenz** [nuxt-ui-pro/saas#6]
Hey, when cloning this repo and running it locally, I got several hydration mismatch errors in my console. I didn't change any code or anything like that. I just installed the dependencies. Any plan to fix this issue.
![image](https://github.com/nuxt-ui-pro/saas/assets/34741282/f59e32eb-7643-4313-bf1f-be521e434de5)

**Comment by benjamincanac** [comment]
Do you have the `vue` resolution set to `3.3.13` or did you remove it?

**Comment by nicogenz** [comment]
No i did not remove it, i still have it. I just cloned this repo and started the dev server, when getting this error.

**Comment by benjamincanac** [comment]
Mmmh this is really weird, I cannot reproduce. This is for sure a Vue 3.4 hydration error, you shouldn't have this with `vue` pinned to `3.3`.

What package manager are you using? The `resolutions` key is for `pnpm` and `yarn`, if you're using `npm` I'd suggest to use `overrides` instead of `resolutions`.

**Comment by nicogenz** [comment]
You are right. This was the issue. I was using `npm` and it installed the latest vue version, `3.4.x`. I changed it to install `3.3.13` and now it is working as inteded.

Thank you very much. Keep up the good work
